spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2
    username: sa
    password:
  servlet:
    multipart:
      enabled: true
      location: C:\\temp
      max-request-size: 30MB
      max-file-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: h2

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console